[package]
name = "data_base"
version = "0.1.0"
authors = ["Rohit Choudhari <itsgood37@ymail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
