[package]
name = "database"
version = "0.1.0"
authors = ["Rohit Choudhari <https://www.github.com/InfernapeXavier>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
lalrpop = "0.18.1"

[dependencies]
lalrpop-util = "0.18.1"
regex = "1"
