[env]
RUST_BACKTRACE = "1"

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.project]
script = [
    "rm -r src/scratch/*.exe",
    "rm -r src/scratch/*.pdb",
    "rm -r src/*.exe",
    "rm -r src/*.pdb",
]

dependencies = [
    "format",
    "build",
    "test"
]